# Generated by Django 5.0.7 on 2024-07-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ariza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davlat', models.CharField(blank=True, max_length=255)),
                ('viloyat', models.CharField(blank=True, max_length=255)),
                ('manzil', models.CharField(blank=True, max_length=255)),
                ('familya', models.CharField(blank=True, max_length=255)),
                ('ism', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('telefon_nomer', models.CharField(blank=True, max_length=255)),
                ('tugatgan_oligoh', models.CharField(blank=True, max_length=255)),
                ('fuqaroligi', models.CharField(blank=True, max_length=255)),
                ('telegram_name', models.CharField(blank=True, max_length=255)),
                ('whatsapp_name', models.CharField(blank=True, max_length=255)),
                ('vaqt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qolanma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='qolanma')),
            ],
        ),
    ]
