# Generated by Django 5.0.7 on 2024-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0002_rename_davlat_ariza_sharif_remove_ariza_manzil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='rasm',
            field=models.FileField(blank=True, upload_to='rasm'),
        ),
    ]
