# Generated by Django 5.1.1 on 2024-09-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ariza', '0003_ariza_rasm'),
    ]

    operations = [
        migrations.AddField(
            model_name='ariza',
            name='daraja',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ariza',
            name='yonalish',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
